[tool.poetry]
name = "opencem"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.6"
appdirs = "==1.4.3"
atomicwrites = "==1.3.0"
attrs = "==19.1.0"
cycler = "==0.10.0"
holidays = "==0.9.10"
kiwisolver = "==1.0.1"
matplotlib = "==3.0.3"
more-itertools = "==7.0.0"
nose = "==1.3.7"
numpy = "==1.16.2"
pandas = "==0.24.2"
pluggy = "==0.9.0"
ply = "==3.11"
py = "==1.8.0"
PyMySQL = "==0.9.3"
Pyomo = "==5.6.1"
pyparsing = "==2.3.1"
pytest = "==4.4.0"
python-dateutil = "==2.8.0"
pytz = "==2018.9"
PyUtilib = "==5.6.5"
scipy = "==1.2.1"
si-prefix = "==1.2.2"
six = "==1.12.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
